_target_: src.models.regressor.RegressorModel

net:
  _target_: src.models.components.base.RegressorNet
  backbone:
    _target_: torchvision.models.resnet18 # change model on this
    pretrained: True
  bins: 2

optimizer: adam

lr: 0.0001
momentum: 0.9
w: 0.8
alpha: 0.2